export { fitScale, thumbScale } from './helpers'
export { DeckRoot } from './Root'
export { DeckSlideList } from './SlideList'
export { DeckStage } from './Stage'
export { DeckCanvas } from './Canvas'
export { DeckTool } from './Tool'
export { newTextElement, moveBounds } from './helpers'
export { editorReducer, initialEditorState } from './editorState'
export { snapshotCmd, patchTextCmd, moveCmd, addElementCmd } from './commands'
